// Spanish agent bios + roles. Generated by
// `scripts/extract-i18n-content.mjs`. Re-run when agents change in Sanity.
// Manual edits will be overwritten.
//
// Note: `name` and contact info live in Sanity and are read directly by
// the agent components. Only `bio` and `role` are translatable.

export interface AgentCopy {
  bio?: string;
  role?: string;
}

export const agentesEs: Record<string, AgentCopy> = {
  "andrea-alvarado": {
    role: "Agente",
  },
  "carlos-bustamante": {
    role: "Agente",
  },
};
