// Spanish neighborhood seoBlocks. Generated by
// `scripts/extract-i18n-content.mjs`. Re-run when neighborhoods change in Sanity.
// Manual edits will be overwritten.

export interface NeighborhoodCopy {
  seoBlock: string;
}

export const neighborhoodsEs: Record<string, NeighborhoodCopy> = {
  "albrook": {
    seoBlock: "Albrook es un barrio tranquilo y arbolado de Panama City, próximo al aeropuerto doméstico Marcos Gelabert y al centro comercial Albrook Mall. Con casas y apartamentos a precios competitivos, es ideal para familias que buscan amplitud y naturaleza dentro de la ciudad.",
  },
  "alto-del-chase": {
    seoBlock: "Alto del Chase es una urbanización residencial en el norte de Panama City, con casas amplias, calles arboladas y un ambiente familiar alejado del ruido urbano. Ideal para quienes buscan espacio y privacidad dentro del área metropolitana, con acceso rápido a los principales corredores viales de la ciudad.",
  },
  "altos-del-golf": {
    seoBlock: "Altos del Golf es un barrio residencial tranquilo y arbolado próximo al Club de Golf de Panamá. Con casas amplias y apartamentos en entorno verde, es ideal para familias que buscan tranquilidad a pocos minutos del centro de la ciudad.",
  },
  "amador": {
    seoBlock: "Amador es la calzada que conecta tres islas históricas con el centro de Panama City, con marinas, restaurantes y vistas panorámicas al Puente de las Américas y la entrada del canal de Panamá. Un entorno único donde la vida frente al mar convive con la energía de la ciudad a apenas minutos del centro financiero.",
  },
  "avenida-balboa": {
    seoBlock: "Avenida Balboa es el paseo marítimo de Panama City, con torres residenciales frente al mar y acceso directo al Cinta Costera. Una ubicación central con vistas al Pacífico y conexión inmediata a Punta Pacífica, Miraflores y el centro financiero.",
  },
  "bella-vista": {
    seoBlock: "Bella Vista es un barrio residencial céntrico de Panama City con buena conectividad y precios accesibles frente a otras zonas exclusivas. Opción sólida para primera vivienda o inversión en alquiler por su posición entre el centro financiero y las zonas costeras.",
  },
  "calle-50": {
    seoBlock: "Calle 50 es el eje financiero y corporativo de Panama City, con oficinas, bancos, hoteles internacionales y restaurantes ejecutivos. La zona más demandada para oficinas en venta y alquiler en toda la ciudad.",
  },
  "carrasquilla": {
    seoBlock: "Carrasquilla es un barrio residencial y comercial consolidado de Panama City, conocido por su ambiente tranquilo, sus calles con servicios de todo tipo y su excelente conectividad con el resto de la ciudad. Una zona accesible y bien ubicada, muy buscada para primera vivienda o inversión en alquiler a largo plazo.",
  },
  "coco-del-mar": {
    seoBlock: "Coco del Mar es un barrio residencial exclusivo entre Punta Paitilla y San Francisco, conocido por su tranquilidad y la calidad de sus edificios. Con acceso directo a la Cinta Costera y vistas parciales al mar, es una zona muy demandada para residencia familiar.",
  },
  "condado-del-rey": {
    seoBlock: "Condado del Rey es una de las urbanizaciones más activas del norte de Panama City, con universidades, centros comerciales y una infraestructura consolidada que la convierten en una zona muy atractiva para familias jóvenes y estudiantes. Propiedades espaciosas a precios competitivos en un entorno de crecimiento sostenido.",
  },
  "coronado": {
    seoBlock: "Coronado es el balneario más conocido de Panama, a 80 km de Panama City. Con casas de playa, condominios frente al mar y un entorno de resort, es el destino preferido para segunda vivienda y alquiler vacacional en el Pacífico panameño.",
  },
  "costa-del-este": {
    seoBlock: "Costa del Este es la urbanización planificada más moderna de Panama City, con amplias avenidas, parques y torres residenciales de lujo. Ideal para familias que buscan un entorno tranquilo con todas las comodidades urbanas, a 15 minutos del aeropuerto Tocumen.",
  },
  "el-cangrejo": {
    seoBlock: "El Cangrejo es el barrio más cosmopolita y bohemio de Panama City, con una vibrante escena gastronómica y cultural. Muy demandado para alquiler de apartamentos por su ambiente urbano y su posición central.",
  },
  "farallon": {
    seoBlock: "Farallón es el destino de playa más exclusivo del Pacífico panameño, a tan solo 90 minutos de Panama City por la Autopista Panamericana. Sus playas de arena blanca y aguas cálidas albergan residencias de lujo, condominios frente al mar y resorts internacionales de primer nivel. La zona concentra los proyectos inmobiliarios costeros de mayor plusvalía del país, con propiedades que van desde apartamentos en torre hasta villas privadas con piscina y acceso directo al Océano Pacífico.",
  },
  "loma-alegre": {
    seoBlock: "Loma Alegre es un barrio residencial tranquilo en el norte de Panama City, con casas y edificios de apartamentos rodeados de zonas verdes y buena conectividad hacia el centro. Un entorno apacible donde la vida familiar fluye lejos del tráfico intenso, con precios accesibles para quienes buscan amplitud sin salir de la ciudad.",
  },
  "los-andes": {
    seoBlock: "Los Andes es un barrio residencial popular de Panama City con una comunidad establecida, comercio de cercanía y fácil acceso a los principales corredores viales de la ciudad. Una zona práctica y accesible para primera vivienda, con una oferta amplia de apartamentos y casas a precios de los más competitivos del mercado.",
  },
  "marbella": {
    seoBlock: "Marbella es un barrio corporativo y residencial en el corazón del centro financiero de Panama City, a pasos de Calle 50 y el Área Bancaria. Muy demandado para oficinas en alquiler y apartamentos ejecutivos.",
  },
  "obarrio": {
    seoBlock: "Obarrio es uno de los barrios más dinámicos de Panama City, con una mezcla de residencias, oficinas, restaurantes y locales comerciales en el corazón de la ciudad. Zona muy demandada para alquiler de apartamentos y locales comerciales por su posición central.",
  },
  "panama-pacifico": {
    seoBlock: "Panamá Pacífico es una ciudad planificada de alto estándar ubicada en la antigua base aérea de Howard, a 20 minutos del centro de Panama City. Con amplias avenidas, parques, colegios internacionales y una zona franca activa, es una de las apuestas de mayor crecimiento del país. Sus apartamentos y casas combinan modernidad, espacios verdes y precios más accesibles que el centro financiero, convirtiéndola en destino ideal para familias y profesionales expatriados.",
  },
  "punta-pacifica": {
    seoBlock: "Punta Pacífica es el barrio más exclusivo de Panama City, con torres residenciales frente al Pacífico y acceso inmediato al Hospital Punta Pacífica, centros comerciales y el Corredor Sur. Con más de 55 propiedades disponibles en Panamares, es la zona con mayor oferta de apartamentos, penthouses y oficinas de lujo en la ciudad.",
  },
  "punta-paitilla": {
    seoBlock: "Punta Paitilla es uno de los barrios residenciales más consolidados de Panama City, conocido por sus torres frente a la bahía y su tranquilidad a pocos minutos del centro financiero. Panamares tiene más de 13 propiedades disponibles entre apartamentos y terrenos en esta zona exclusiva.",
  },
  "rio-mar": {
    seoBlock: "Río Mar es el complejo residencial de playa más exclusivo del Pacífico central panameño, a unos 100 km de Panama City, con torres frente al Océano Pacífico, acceso directo a la playa y un entorno de resort de alto nivel. La opción preferida para segunda vivienda o alquiler vacacional en la costa pacífica de Panamá.",
  },
  "san-francisco": {
    seoBlock: "San Francisco es un barrio residencial y comercial consolidado de Panama City, con una amplia oferta de locales comerciales, apartamentos y servicios. Muy bien comunicado con Calle 50, Marbella y el Corredor Sur.",
  },
  "santa-maria": {
    seoBlock: "Santa María es la urbanización de lujo más exclusiva de la periferia de Panama City, con campos de golf, casas de alta gama y un entorno completamente planificado. Ideal para familias que buscan privacidad, seguridad y el mejor estilo de vida suburbano de Panama.",
  },
  "versalles": {
    seoBlock: "Versalles es una urbanización residencial familiar en el norte de Panama City, con casas amplias, parques y un ambiente seguro y tranquilo que la hace muy popular entre familias con hijos. Una zona de crecimiento sostenido con buena oferta de casas a precios más accesibles que las zonas costeras y el centro financiero.",
  },
  "via-porras": {
    seoBlock: "Vía Porras es uno de los corredores más transitados del este de Panama City, con apartamentos, locales comerciales y restaurantes a lo largo de una avenida de alta conectividad. Su cercanía con el Corredor Sur, el aeropuerto Tocumen y el parque Omar la convierten en una zona muy demandada para vivir y para alquiler de locales.",
  },
};
