import type { MetadataRoute } from "next";
import { sanityFetch } from "@/sanity/lib/client";
import { groq } from "next-sanity";
import { CATEGORIES } from "@/lib/categories";
import { NEIGHBORHOODS } from "@/lib/neighborhoods";
import { BASE_URL } from "@/lib/config";

interface PropertySlim {
  slug: string;
  propertyType: string;
  businessType: string;
  zone: string | null;
  updatedAt: string;
}

interface AgentSlim {
  slug: string;
  updatedAt: string;
}

interface GuideSlim {
  slug: string;
  updatedAt: string;
}

// ── Sitemap index: 3 separate sitemaps ────────────────────────────────────────
// /sitemap.xml         → index (auto-generated by Next.js)
// /sitemap/0.xml       → listings (Tier 4)
// /sitemap/1.xml       → category + neighborhood pages (Tier 0–3)
// /sitemap/2.xml       → content pages (agents, guides, barrios, static)
export function generateSitemaps() {
  return [{ id: 0 }, { id: 1 }, { id: 2 }];
}

export default async function sitemap({
  id,
}: {
  id: number;
}): Promise<MetadataRoute.Sitemap> {
  // ── Shared data fetches (Next.js dedupes across calls) ────────────────────
  const activeProperties = await sanityFetch<PropertySlim[]>(groq`
    *[_type == "property" && listingStatus == "activa" && noindex != true] {
      "slug": slug.current,
      propertyType,
      businessType,
      "zone": zone,
      "updatedAt": _updatedAt
    }
  `);

  // ── Sitemap 0: Listings (Tier 4) ──────────────────────────────────────────
  if (id === 0) {
    return activeProperties.map((p) => ({
      url: `${BASE_URL}/propiedades/${p.slug}`,
      lastModified: new Date(p.updatedAt),
      changeFrequency: "weekly",
      priority: 0.8,
    }));
  }

  // ── Sitemap 1: Category + neighborhood pages (Tier 0–3) ───────────────────
  if (id === 1) {
    const categoryCountMap = new Map<string, number>();
    const geoTypeCountMap = new Map<string, number>();

    for (const p of activeProperties) {
      const catKey = `${p.propertyType}|${p.businessType}`;
      categoryCountMap.set(catKey, (categoryCountMap.get(catKey) ?? 0) + 1);
      if (p.zone) {
        const geoKey = `${p.propertyType}|${p.businessType}|${p.zone}`;
        geoTypeCountMap.set(geoKey, (geoTypeCountMap.get(geoKey) ?? 0) + 1);
      }
    }

    return [
      // Tier 0 — Homepage
      {
        url: BASE_URL,
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 1.0,
      },
      // Tier 1 — Intent hubs
      {
        url: `${BASE_URL}/propiedades-en-venta`,
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.9,
      },
      {
        url: `${BASE_URL}/propiedades-en-alquiler`,
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.9,
      },
      // Tier 2 — Category pages (2+ listings)
      ...CATEGORIES.flatMap((cat) => {
        const count = categoryCountMap.get(`${cat.propertyType}|${cat.businessType}`) ?? 0;
        if (count < 2) return [];
        return [{
          url: `${BASE_URL}/${cat.slug}`,
          lastModified: new Date(),
          changeFrequency: "daily" as const,
          priority: 0.85,
        }];
      }),
      // Tier 3 — Geo-type pages (2+ listings)
      ...CATEGORIES.flatMap((cat) =>
        NEIGHBORHOODS.flatMap((nbh) => {
          const count = geoTypeCountMap.get(`${cat.propertyType}|${cat.businessType}|${nbh.name}`) ?? 0;
          if (count < 2) return [];
          return [{
            url: `${BASE_URL}/${cat.slug}/${nbh.slug}`,
            lastModified: new Date(),
            changeFrequency: "daily" as const,
            priority: 0.8,
          }];
        })
      ),
    ];
  }

  // ── Sitemap 2: Content pages ──────────────────────────────────────────────
  const [agents, guides] = await Promise.all([
    sanityFetch<AgentSlim[]>(groq`
      *[_type == "agent"] { "slug": slug.current, "updatedAt": _updatedAt }
    `),
    sanityFetch<GuideSlim[]>(groq`
      *[_type == "guide"] { "slug": slug.current, "updatedAt": _updatedAt }
    `),
  ]);

  return [
    // Static content
    {
      url: `${BASE_URL}/agentes`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.6,
    },
    {
      url: `${BASE_URL}/guias`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.65,
    },
    {
      url: `${BASE_URL}/sobre-nosotros`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: `${BASE_URL}/contacto`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    // Neighborhood guides (2+ listings only)
    ...NEIGHBORHOODS.filter((nbh) =>
      activeProperties.filter((p) => p.zone === nbh.name).length >= 2
    ).map((nbh) => ({
      url: `${BASE_URL}/barrios/${nbh.slug}`,
      lastModified: new Date(),
      changeFrequency: "weekly" as const,
      priority: 0.7,
    })),
    // Agent profiles
    ...agents.map((a) => ({
      url: `${BASE_URL}/agentes/${a.slug}`,
      lastModified: new Date(a.updatedAt),
      changeFrequency: "monthly" as const,
      priority: 0.6,
    })),
    // Guide articles
    ...guides.map((g) => ({
      url: `${BASE_URL}/guias/${g.slug}`,
      lastModified: new Date(g.updatedAt),
      changeFrequency: "monthly" as const,
      priority: 0.65,
    })),
  ];
}
